algoritmo "CalculoPeca"
// Função : Solicitar o valor da peça, quantidade comprada e total da compra
// Autor : murilo Gonçalves
// Data : 10/05/2022
// Seção de Declarações 
var

valor,qnt,total:real

inicio
// entrada

escreval("digite a quantidadede peças compradas")
leia(qnt)
escreval("Digite o valor unítario de cada peça")
leia(valor)
//processamento
total<-valor*qnt

//saida
escreval("O valor total da sua compra é:",total)
// seção de comandos

fimalgoritmo
